project:
  type: website

website:
  title: "Lykta"
  navbar:
    right:
      - about.qmd
      - products/products.qmd
      # - icon: github
      #   href: https://github.com/
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



